#Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Cocktail.create(name: "Mojito")
Cocktail.create(name: "Sex on the beach")
Cocktail.create(name: "Petit planteur")
